### ISSUE TITLE
Assembler.Cache do not contains ElementDefinition read from a JSON DAL

### ISSUE THREAD

**Issue by andrtose** [RHEAGROUP/CDP4-SDK-Community-Edition#114]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-SDK
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I Read a JSON file I cannot find in the Session.Assembler.Cache any of the ElementDefinitions stored in the OpenIteration. The Cache contains Things that refer to another Iteration Iid.
I can Read the EngineeringModel and it has a complete (and correct) structure inside.

If I open the zip file with CDP4 it works so I assumed the zip is not corrupted.

### Steps to Reproduce

```
requestedEngineeringModel = new EngineeringModel(iid: currentEngineeringModelSetup.EngineeringModelIid, cache: CurrentSession.Assembler.Cache, iDalUri: uri);

{ EngineeringModelSetup = currentEngineeringModelSetup; };

var requestedIteration = new Iteration(iid: currentIterationSetup.IterationIid, cache: CurrentSession.Assembler.Cache, iDalUri: uri);

requestedEngineeringModel.Iteration.Add(requestedIteration);

await CurrentSession.Read(requestedIteration, selectedDomain);

CurrentEngineeringModel = CurrentSession.Assembler.Cache[requestedEngineeringModel.CacheKey].Value as EngineeringModel;
```

### System Configuration

- CDP4 version:
  - [ ] CDP4Common:         
  - [ ] CDP4JsonSerializer: 
  - [ ] CDP4Dal:            
  - [X] CDP4JsonFileDal:    
  - [ ] CDP4ServicesDal:    
  - [ ] CDP4WspDal:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version: 4.8
- Additional information:

**Comment by lxatrhea** [comment]
Contact the issuer and go from there.

**Comment by lxatrhea** [comment]
@andrtose 
First question would be: Is this still an issue, or have you already found a workaround, for example?

If it is still an issue, then based on the code in the **Steps to Reproduce** text of this issue I also cannot fully understand what the problem is.
I think it's best that we have a call to take a look at the rest of the code. 
Especially on the context of `CurrentSession`,  `currentEngineeringModelSetup` and `currentIterationSetup`.

**Comment by andrtose** [comment]
Sorry for the very late reply, I have to investigate better this because now it works, maybe something is wrong concerning the context of CurrentSession, that is not passed correctly in my code.

**Comment by lxatrhea** [comment]
No problem. 
Please let us know if any help is needed.
