### ISSUE TITLE
Performance optimization of CDP4Common.SiteDirectoryData.Category.AllDerivedCategories()

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-SDK-Community-Edition#138]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In situations where IsMemberOf() methods for ICategorizableThings are used extensively in a short time, we should do some performance optimizations.
In the program flow the `CDP4Common.SiteDirectoryData.Category.AllDerivedCategories()` method is used very often, and that method reads all Category instances from the ISession.Assembler.Cache, which in the end takes a lot of computer resources.

We should make the method execute faster, for example by not using the ISession.Assembler.Cache anymore, or by caching the result of the call to ISession.Assembler.Cache in a temporary local/shared variable that can be reused when needed, or in another smart way.

**Comment by samatrhea** [comment]
agreed, using the cache and going through all the data is not very optimal
