### ISSUE TITLE
The CDP4Common.Helpers.NestedElementTreeGenerator class has no proper function for returning row view of Nested Parameters

### ISSUE THREAD

**Issue by oiynick** [RHEAGROUP/CDP4-SDK-Community-Edition#21]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The issue is related to the enhancements section and describes the lack of functionality of the class "CDP4Common.Helpers.NestedElementsTreeGenerator". On its own the class could not return the row view of the Nested Parameters the Option has.

**Comment by samatrhea** [comment]
fixed in dd7872837dbde6c585bfd6c72ce0202c8d3db5cf  in PR #22
