### ISSUE TITLE
When a Transaction is finalized, resulting in an OperationContainer that is empty, the Dal should not send it of to the data source

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-SDK-Community-Edition#46]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The registration of Add, Delete and Update operation on a Transaction may result in a no-op when basically nothing is changed to the Things being registered. If this is the case, the Dal.Write should not communicate with the datasource because nothing will happen. This improvement will enhance performance by not sending empty POST messages to the data-source

### Steps to Reproduce
NA

### System Configuration
NA

- CDP4-SDK version 5

**Comment by samatrhea** [comment]
monitored AB#2

**Comment by samatrhea** [comment]
diff up at D1517

**Comment by alexatrhea** [comment]
Accepted for merge.
