### ISSUE TITLE
Add convience methods to query reference data from a chain of Rdls

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-SDK-Community-Edition#48]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In order to harmonize the way reference data is queried from the POCO's a set of convenience methods should be added to the ReferenceDataLibrary class to query contained reference data (per type) from the chain of RDL's. The return type should be an IEnumerable of te queried type

### Steps to Reproduce
NA

### System Configuration

- CDP4 version:
  - [x] CDP4Common:         3.0.0

**Comment by samatrhea** [comment]
diff up at D1492, @IevhenIkonnykov  can you also have a look that when this is accepted in the C# SDK you also take care of this in the Java SDK?

**Comment by IevhenIkonnykov** [comment]
Okay, I will.

**Comment by IevhenIkonnykov** [comment]
It is done.
