### ISSUE TITLE
PermissionService in CDP4DAL lines that should be deleted.

### ISSUE THREAD

**Issue by IevhenIkonnykov** [RHEAGROUP/CDP4-SDK-Community-Edition#51]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
PermissionService in CDP4DAL lines 147 and 152 contain unreachable code that should be deleted.
### Steps to Reproduce
See the source code.
### System Configuration
Does not matter.

- CDP4 version:
  - [ ] CDP4Common:         
  - [ ] CDP4JsonSerializer: 
  - [ ] CDP4Dal:            
  - [ ] CDP4JsonFileDal:    
  - [ ] CDP4ServicesDal:    
  - [ ] CDP4WspDal:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by alexatrhea** [comment]
https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/blob/development/CDP4Dal/Permission/PermissionService.cs#L147

https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/blob/development/CDP4Dal/Permission/PermissionService.cs#L152

For ref.

**Comment by IevhenIkonnykov** [comment]
Lines 542-545 are not really useful, because line 540 
var baseType = StaticMetadataProvider.BaseType(thingType.ToString());
will throw an exception for not existing type. There is no chance for empty or null string.

**Comment by IevhenIkonnykov** [comment]
In general PermissionService contains a lot of duplicate code that could be refactored. For details how it is refactored in Java implementation see https://github.com/RHEAGROUP/CDP4-SDKJ-Community-Edition/tree/development/cdp4dal/src/main/java/cdp4dal/permission/PermissionServiceImpl.java

**Comment by samatrhea** [comment]
@IevhenIkonnykov  the above link is broken, has the file been moved?
