### ISSUE TITLE
Update documentation of CDP4DAL.DAL.cs

### ISSUE THREAD

**Issue by IevhenIkonnykov** [RHEAGROUP/CDP4-SDK-Community-Edition#53]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Dal.TryExtractIterationIdfromUri Says that throws an exception, but actually swallows it.
OperationContainerFileVerification has typos "machtches, contenthash".
Method TryExtractIterationIdfromUri should follow a notation and be TryExtractIterationIdFromUri.
The class duplicates all methods from IDAL interface and does not implement them. This duplication code could be omitted.

### Steps to Reproduce
See source code.

### System Configuration
Does not matter.

- CDP4 version:
  - [ ] CDP4Common:         
  - [ ] CDP4JsonSerializer: 
  - [ ] CDP4Dal:            
  - [ ] CDP4JsonFileDal:    
  - [ ] CDP4ServicesDal:    
  - [ ] CDP4WspDal:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by samatrhea** [comment]
docs updated in d28c3912f33912a9a99b16f5c7554b65438885bb, changing the name of the method, even though now it does not follow the naming convention, is a non backwards compatible change, We'll do it, but at a time when we have more things to fix that are more fundamental. Regarding the use of an abstract class that implements and interface, this is a design choice. The abstract Dal class implements a set of common methods that are common to all it's subclasses. This will not be changed.

**Comment by IevhenIkonnykov** [comment]
I understand the design. I checked it and it is an interesting difference between Java and C#. In Java if abstract class implements an interface it does not have to implement interface's methods, they will be taken as abstract by default, but I see that it is not the case in C#.

**Comment by IevhenIkonnykov** [comment]
I also have to add that Dal is not covered with tests well. Only one method is covered, but it has 7 implemented methods.

**Comment by samatrhea** [comment]
@IevhenIkonnykov code coverage will then indeed need to go up

**Comment by samatrhea** [comment]
code coverage increased in 31bb24e84ab62c4f603e24b2561ba40d85fdb7ee
