### ISSUE TITLE
Verify that when line breaks are present in the values of ParameterValueSet the serialization and deserialization works as expected

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-SDK-Community-Edition#66]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
related to issue https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/185 where a problem occurs when users make use of ALT+ENTER in an Excel cell

### Steps to Reproduce
see https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/185

### System Configuration

- CDP4 version:
  - [ ] CDP4Common:         
  - [ ] CDP4JsonSerializer: 
  - [ ] CDP4Dal:            
  - [ ] CDP4JsonFileDal:    
  - [ ] CDP4ServicesDal:    
  - [ ] CDP4WspDal:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by lxatrhea** [comment]
See #68

**Comment by lxatrhea** [comment]
Another revision was needed for some extra special characters that need to be (un)escaped.
