### ISSUE TITLE
Incorrect type check for Thing in SDK OrderedItemList

### ISSUE THREAD

**Issue by hpdekoning** [RHEAGROUP/CDP4-SDK-Community-Edition#82]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
At https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/blob/fce21a2b9bed488be13eac2533f301653a84a9ff/CDP4Common/Types/OrderedItemList.cs#L566

In `OrderedItemList.Add(...)` the comparison `if (typeof(T) == typeof(Thing))` is incorrect because it only checks that the type of the incoming `item` is directly a `Thing`, not one of its subtypes.

The correct condition is `if (item is Thing)` which properly checks that the `item` is a `Thing` or any of its subtypes. Alternatively `typeof(T).IsSubclassOf(typeof(Thing))` can be used, if you are sure `T` cannot be `Thing` but must be one of its subtypes.

### Steps to Reproduce
None, found by code inspection.

### System Configuration
Any code that uses the C# SDK.

  - CDP4 version: 
  - [x] CDP4Common: development branch     
  - [ ] CDP4JsonSerializer: 
  - [ ] CDP4Dal:            
  - [ ] CDP4JsonFileDal:    
  - [ ] CDP4ServicesDal:    
  - [ ] CDP4WspDal:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information: Please check for other possible occurrences of the same condition.

**Comment by samatrhea** [comment]
we need to add a unit test to verify correct behavior. I think that by setting **ReferenceDataLibrary.baseUnit** and **ReferenceDataLibrary.baseQuantityKind** we have a concrete example where this may be an issue (the test can be written on SiteReferenceDataLibrary)

**Comment by alexatrhea** [comment]
@hpdekoning it would be good if you could verify that the issue is indeed resolved.
