### ISSUE TITLE
Create a C# sample application.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-SDK-Community-Edition#88]
As a first iteration this should be identical to the console app already made for the Java SDK.

There is quite a need for this as several other projects such as DEHP that have partners that would like to see proper use of the C# SDK without digging into IME code.

**Comment by samatrhea** [comment]
have a look here: https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition-Samples
