### ISSUE TITLE
PermissionService has a bug for write permission in some cases

### ISSUE THREAD

**Issue by IevhenIkonnykov** [RHEAGROUP/CDP4-SDK-Community-Edition#92]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
PermissionService on lines 398 and 507 does not pass a container of the thing, but the thing itself. It might have happened due to a misleading parameter name for a thing. These lines should be fixed. The fix will produce a test fail in PermissionServiceTestFixture  on line 231. Also lines 212 and 213 are identical. On line 212 "CanWrite" method should be substituted with "CanRead".

### Steps to Reproduce
See the source code.

### System Configuration
Does not matter

- CDP4 version:
  - [ ] CDP4Common:         
  - [ ] CDP4JsonSerializer: 
  - [ ] CDP4Dal:            
  - [ ] CDP4JsonFileDal:    
  - [ ] CDP4ServicesDal:    
  - [ ] CDP4WspDal:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by alexatrhea** [comment]
https://github.com/RHEAGROUP/CDP4-SDKJ-Community-Edition/pull/42
