### ISSUE TITLE
Using of Deprecated Things

### ISSUE THREAD

**Issue by andrtose** [RHEAGROUP/CDP4-SDK-Community-Edition#99]
Dear All,

by using SDK on my application I "successfully" created a Coumpound Parameter Type with a component depending on a (currently)deprecated parameter. 
Is it all right ?

Kind regards,
Andrea

**Comment by samatrhea** [comment]
10-25 does not state that this is not allowed, so yes, that should be fine. When you implement in a GUI, you could filter out deprecated components so users do not make this "mistake"
